language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm
  
node_js:
  - '14.16.0'

git:
  depth: 3

env:
  global:
    - PROD=''

before_install:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
    PROD='--prod';
    fi

script:
  - npm install netlify-cli
  - npm run build
  - netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_AUTH $PROD --dir=build --message='$TRAVIS_COMMIT_MESSAGE'