language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm
  
node_js:
  - '13.0.1'

git:
  depth: 3

env:
  global:
    - PROD=''

before_install:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
    PROD='--prod';
    fi

script:
  - npm install netlify-cli
  - npm run build
  - netlify link $NETLIFY_SITE
  - netlify deploy $PROD --dir=build --message='$TRAVIS_COMMIT_MESSAGE'

